### ISSUE TITLE
LWJGL 3.2.0 12: UnsupportedOperationException/NullPointerException

### ISSUE THREAD

**Issue by gudenau** [LWJGLX/debug#18]
When using LWJGL 3.2.0 build 12 on OpenJDK 11 with the debug library it throws several `java.lang.UnsupportedOperationException` during class transformations and a `java.lang.NullPointerException` inside `org.lwjgl.opengl.GL.createCapabilities`.

Neither of these exceptions are thrown while LWJGLX are used as an agent.

java --version
```
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

Java output:
```
/usr/lib/jvm/jdk-11/bin/java -javaagent:lwjglDebug/lwjglx-debug-1.0.0.jar -javaagent:/home/gudenau/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4892.20/lib/idea_rt.jar=43771:/home/gudenau/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4892.20/bin -Dfile.encoding=UTF-8 -p /home/gudenau/Desktop/projects/java/-snip-/Client/target/classes:/home/gudenau/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/home/gudenau/Desktop/projects/java/-snip-/IPC/target/classes:/home/gudenau/Desktop/projects/java/-snip-/Protocol/target/classes:/home/gudenau/.m2/repository/org/lwjgl/lwjgl/3.2.0/lwjgl-3.2.0.jar:/home/gudenau/.m2/repository/org/lwjgl/lwjgl-glfw/3.2.0/lwjgl-glfw-3.2.0.jar:/home/gudenau/.m2/repository/org/lwjgl/lwjgl-opengl/3.2.0/lwjgl-opengl-3.2.0.jar:/home/gudenau/.m2/repository/org/lwjgl/lwjgl-stb/3.2.0/lwjgl-stb-3.2.0.jar:/home/gudenau/.m2/repository/org/lwjgl/lwjgl/3.2.0/lwjgl-3.2.0-natives-linux.jar:/home/gudenau/.m2/repository/org/lwjgl/lwjgl-glfw/3.2.0/lwjgl-glfw-3.2.0-natives-linux.jar:/home/gudenau/.m2/repository/org/lwjgl/lwjgl-opengl/3.2.0/lwjgl-opengl-3.2.0-natives-linux.jar:/home/gudenau/.m2/repository/org/lwjgl/lwjgl-stb/3.2.0/lwjgl-stb-3.2.0-natives-linux.jar -m net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client
[LWJGL] Version: 3.2.0 build 12
[LWJGL] 	 OS: Linux v4.18.16
[LWJGL] 	JRE: 11 amd64
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v11+28 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: /tmp/lwjglgudenau/3.2.0-build-12/liblwjgl.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglgudenau/3.2.0-build-12/liblwjgl.so
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator. Using the system default.
[LWJGL] MemoryUtil allocator: DebugAllocator
[LWJGL] Loading library: glfw
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: /tmp/lwjglgudenau/3.2.0-build-12/libglfw.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglgudenau/3.2.0-build-12/libglfw.so
java.lang.UnsupportedOperationException
	at org.lwjglx.debug.org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.lwjglx.debug.Agent.transform_(Agent.java:205)
	at org.lwjglx.debug.Agent.transform(Agent.java:71)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1095)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.ui.key.KeyLayoutManager.loadLayout(KeyLayoutManager.java:81)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.ui.key.KeyLayoutManager.<clinit>(KeyLayoutManager.java:20)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.start(Client.java:35)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.lambda$main$0(Client.java:25)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.UnsupportedOperationException
	at org.lwjglx.debug.org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.lwjglx.debug.Agent.transform_(Agent.java:205)
	at org.lwjglx.debug.Agent.transform(Agent.java:71)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1095)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.ui.key.KeyLayoutManager.loadLayout(KeyLayoutManager.java:83)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.ui.key.KeyLayoutManager.<clinit>(KeyLayoutManager.java:20)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.start(Client.java:35)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.lambda$main$0(Client.java:25)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.UnsupportedOperationException
	at org.lwjglx.debug.org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.lwjglx.debug.Agent.transform_(Agent.java:205)
	at org.lwjglx.debug.Agent.transform(Agent.java:71)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1095)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.start(Client.java:37)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.lambda$main$0(Client.java:25)
	at java.base/java.lang.Thread.run(Thread.java:834)
[LWJGL] Loading library (system): lwjgl_opengl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: /tmp/lwjglgudenau/3.2.0-build-12/liblwjgl_opengl.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglgudenau/3.2.0-build-12/liblwjgl_opengl.so
[LWJGL] Loading library: libGL.so.1
[LWJGL] 	libGL.so.1 not found in org.lwjgl.librarypath=/tmp/lwjglgudenau/3.2.0-build-12
[LWJGL] 	Loaded from system paths: /usr/lib/x86_64-linux-gnu/libGL.so.1
[LWJGL] Java 9 optimizations enabled
[LWJGL] [GL] Using OpenGL 4.3 for error logging.
[LWJGL] [GL] Warning: A non-debug context may not produce any debug output.
Exception in thread "New Main" java.lang.NullPointerException
	at org.lwjglx.debug.opengl.GL.createCapabilities(GL.java:39)
	at org.lwjglx.debug.$Proxy$5.createCapabilities1(Unknown Source)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.start(Client.java:40)
	at net.gudenau.-snip-.Client/net.gudenau.-snip-.client.Client.lambda$main$0(Client.java:25)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by httpdigest** [comment]
Thanks for the info! Updated library has been pushed to LWJGL's AWS S3. Can you please redownload or rebuild it and try again?

**Comment by gudenau** [comment]
How would I build the jar? I downloaded this today.

**Comment by httpdigest** [comment]
Just redownload (like I said above).
EDIT: Assuming you downloaded it through https://www.lwjgl.org/customize

**Comment by gudenau** [comment]
Thanks for the super quick fix.
