### ISSUE TITLE
Java 18 compatibility

### ISSUE THREAD

**Issue by ScoreUnder** [LWJGLX/debug#33]
I saw there was a pull request to update dependencies for Java 18 compatibility, but even building against 402539ae55f2b5356d63cf58ca073943ca1b8cea using `./mvnw clean package`, the resulting `target/lwjglx-debug-1.0.0.jar` does not seem to work with Java 18. It's exactly what you'd expect:

```
java.lang.IllegalArgumentException: Unsupported class file major version 62
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.lwjglx.debug.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.lwjglx.debug.Agent.transform_(Agent.java:140)
	at org.lwjglx.debug.Agent.transform(Agent.java:65)
[...]
```

Oddly enough, in the source I have, the `new ClassReader` occurs one line later, on line 141, but is reported as being on 140 for reasons I cannot fathom.

There was also one stage of the maven build where it threw an error (not counting the intentional errors in testing), and I'm not sure if it's significant or not:
```
[INFO] --- maven-antrun-plugin:3.1.0:run (default) @ lwjglx-debug ---
[INFO] Executing tasks
[ERROR]      [java] java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:194)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:891)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
```

**Comment by ScoreUnder** [comment]
It seems to have started working and I am not sure how.
